//! Internal helper machinery for [rjava]: currently the safe wrapper around
//! the unsafe JNI registration calls behind native-method registration;
//! future internal utilities live here too.
//!
//! This crate is an implementation detail of `rjava` — you normally never
//! depend on it directly. The user-facing macros
//! ([`rjava::native`](https://docs.rs/rjava/latest/rjava/macro.native.html) /
//! [`rjava::native_inst`](https://docs.rs/rjava/latest/rjava/macro.native_inst.html))
//! live in the `rjava-macros` crate; this crate
//! currently contains [`register_natives`], the internal helper that performs the
//! two JNI calls the `jni` crate (correctly) exposes as `unsafe`:
//!
//! * constructing a [`jni::NativeMethod`] (`from_raw_parts`), and
//! * calling [`jni::Env::register_native_methods`].
//!
//! Both `unsafe` blocks live **here** — attributed to this crate, not to the
//! macro's *use site* — so `rjava`'s own source and the macro expansions stay
//! 100% `unsafe`-free. The `native!`/`native_inst!` proc macros accept two
//! forms: the **type-derived** form (`native!("name", f)` — the JNI signature
//! is derived from the Rust types at runtime, the C ABI is fixed by a shared
//! generic trampoline in `rjava`) and the **explicit-signature** form
//! (`native!("name", "(II)I", f)` — the signature is parsed at compile time
//! and a unique `extern "system"` trampoline is generated whose C parameter
//! and return types are the exact `jni::sys` types for the signature). At
//! call time the trampoline converts the raw JNI arguments into
//! [`rjava::JavaArg`](https://docs.rs/rjava/latest/rjava/enum.JavaArg.html)s and hands them to
//! [`rjava::native::dispatch`](https://docs.rs/rjava/latest/rjava/native/fn.dispatch.html), which runs the user's Rust function. Panics
//! are caught and converted into Java `RuntimeException`s; `Err(…)` results
//! are thrown as Java exceptions too, so nothing unwinds across the FFI
//! boundary.
//!
//! [rjava]: https://docs.rs/rjava

/// Register a batch of native methods on `class` (internal helper).
///
/// This is called by [`rjava::JClass::register_natives`](https://docs.rs/rjava/latest/rjava/struct.JClass.html#method.register_natives); it exists here —
/// and not in `rjava` itself — because the two JNI calls it makes are
/// `unsafe` in the `jni` crate, and `rjava` is `#![forbid(unsafe_code)]`.
///
/// `methods` carries the (name, signature, function-pointer) triples. Each
/// `fn_ptr` must be the address of a trampoline whose C signature matches the
/// JNI signature: the `native!`/`native_inst!` proc macros guarantee exactly
/// that — the explicit-signature form parses the signature at compile time
/// and generates the trampoline, the type-derived form picks a shared generic
/// trampoline whose C signature is the sealed `NativeArg`/`NativeReturn`
/// instantiation for the same Rust types that produce the descriptor — so
/// this holds by construction for every descriptor they produce.
///
/// Errors (e.g. `NoSuchMethodError` when the class has no such `native`
/// method, or a signature mismatch) are reported as `jni::errors::Error`s and
/// surfaced by `rjava`'s exception machinery.
#[doc(hidden)]
pub fn register_natives(
    env: &mut jni::Env<'_>,
    class: &jni::objects::JClass<'_>,
    methods: &[(
        jni::strings::JNIString,
        jni::strings::JNIString,
        *mut std::ffi::c_void,
    )],
) -> jni::errors::Result<()> {
    let mut jni_methods: Vec<jni::NativeMethod<'_>> = Vec::with_capacity(methods.len());
    for (name, sig, fn_ptr) in methods {
        // SAFETY: `fn_ptr` is the address of a trampoline generated by rjava's
        // `native!`/`native_inst!` macros. Those macros parse the JNI signature
        // at compile time and derive the trampoline's C parameter and return
        // types from it, so the function pointer is valid and matches `sig` —
        // precisely the contract of `NativeMethod::from_raw_parts`. The
        // name/sig `JNIStr`s borrow from the caller's slice and stay alive for
        // the lifetime of the returned `NativeMethod` (scoped to this call).
        let nm = unsafe { jni::NativeMethod::from_raw_parts(name, sig, *fn_ptr) };
        jni_methods.push(nm);
    }
    // SAFETY: same argument as above — every function pointer matches its
    // signature by construction, and the static/instance classification is
    // baked into the trampoline the user chose (`native!` drops the `JClass`
    // receiver, `native_inst!` forwards the `JObject` receiver), matching what
    // the JVM expects for each method. The JVM additionally validates the
    // class, name and signature against the class file itself and reports
    // mismatches as `NoSuchMethodError` rather than undefined behavior.
    unsafe { env.register_native_methods(class, &jni_methods) }
}
